-- AlterTable
ALTER TABLE "search" ADD COLUMN     "descText" TEXT,
ALTER COLUMN "whiteInfo" SET DATA TYPE VARCHAR(200),
ALTER COLUMN "blackInfo" SET DATA TYPE VARCHAR(200),
ALTER COLUMN "errDesc" SET DATA TYPE VARCHAR(200);

-- AlterTable
ALTER TABLE "tasks" ADD COLUMN     "cityCode" VARCHAR(20) NOT NULL DEFAULT '';
